## YAML Template.
---

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
  port:8080
  
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      cors-configurations:
        '[/**]':
          allowed-origins: "http://localhost:4200" # Solo uno, no múltiples orígenes
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true
      routes:
      - id: user_full
        uri: lb://businessdomain-userservice
        predicates:
          - Path=/api/users/full/**
        filter:
          - AuthenticationFiltering
      - id: user_service
        uri: lb://businessdomain-userservice
        predicates:
        - Path=/api/users/**
      - id: product_service
        uri: lb://businessdomain-productservice
        predicates:
        - Path=/api/product/**
      - id: pet_service_pets
        uri: lb://businessdomain-petservice
        predicates:
          - Path=/api/pet/**

      - id: pet_service_location
        uri: lb://businessdomain-petservice
        predicates:
          - Path=/api/location/**

      - id: request_service
        uri: lb://businessdomain-requestservice
        predicates:
          - Path=/api/request/**
      - id: match_service
        uri: lb://businessdomain-matchservice
        predicates:
          - Path=/api/match/**
      - id: notification_service
        uri: lb://businessdomain-notificationservice
        predicates:
          - Path=/api/notification/**
      

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG